import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { getDictionary, Locale } from "./dictionaries";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

interface PageProps {
  params: Promise<{
    lang: Locale;
  }>;
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: PageProps)   {

  const { lang } = await params;
  const t = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body
        className={`antialiased`}
      >
        <Navbar t={t}/>
        {children}
        <Footer t={t}/>
      </body>
    </html>
  );
}
